version: '3'
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  level2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - redis